export const menuItems = [
  {
    name: 'Signature Latte',
    description: 'Double espresso, velvet steamed milk, cocoa dust',
    price: 320,
    image: 'https://images.unsplash.com/photo-1573074699584-303c79998c3a?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'coffee',
    available: true,
  },
  {
    name: 'Hand-Poured Pour Over',
    description: 'Single-origin beans, slow dripped to perfection',
    price: 290,
    image: 'https://images.unsplash.com/photo-1561522983-385a76fbb4cb?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'coffee',
    available: true,
  },
  {
    name: 'Golden Mocha',
    description: 'Dark chocolate, espresso and silky foam art',
    price: 340,
    image: 'https://images.unsplash.com/photo-1757839462651-e457481ede49?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'coffee',
    available: true,
  },
  {
    name: 'Butter Croissant',
    description: 'Flaky, 24-layer, baked fresh every sunrise',
    price: 180,
    image: 'https://images.unsplash.com/photo-1714801172470-bf71c2ac1884?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'bakes',
    available: true,
  },
  {
    name: 'Petit Desserts',
    description: 'Tarts, cheesecakes & pastries from our oven',
    price: 210,
    image: 'https://images.unsplash.com/photo-1747829581661-25b6c86db988?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'bakes',
    available: true,
  },
  {
    name: 'Cocoa Bean & Me',
    description: 'Slow reading corner: iced coffee with a good book',
    price: 360,
    image: 'https://images.unsplash.com/photo-1755882941433-935ff9b7ad0e?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'cold',
    available: true,
  },
  {
    name: 'Caramel Cloud Macchiato',
    description: 'Espresso ribboned through vanilla-steamed milk, crowned with caramel drizzle',
    price: 350,
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'coffee',
    available: true,
  },
  {
    name: 'Sparkling Espresso Tonic',
    description: 'Double espresso over tonic water with a twist of orange zest',
    price: 310,
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'coffee',
    available: true,
  },
  {
    name: 'Royal Masala Chai',
    description: 'Slow-brewed black tea with cardamom, ginger and whole spices',
    price: 240,
    image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'tea',
    available: true,
  },
  {
    name: 'Velvet Matcha Latte',
    description: 'Ceremonial matcha whisked into silky steamed milk',
    price: 330,
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'tea',
    available: true,
  },
  {
    name: 'Earl Grey Orchid',
    description: 'Bergamot black tea with delicate vanilla orchid notes',
    price: 260,
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'tea',
    available: true,
  },
  {
    name: 'Sunset Iced Tea',
    description: 'Chilled black tea, lemon and a whisper of jasmine',
    price: 250,
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'tea',
    available: true,
  },
  {
    name: 'Iced Hazelnut Cold Brew',
    description: '24-hour slow-steeped cold brew over ice with hazelnut',
    price: 340,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'cold',
    available: true,
  },
  {
    name: 'Salted Caramel Iced Latte',
    description: 'Iced espresso, milk and salted caramel silk',
    price: 360,
    image: 'https://images.unsplash.com/photo-1521302200778-33500795e128?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'cold',
    available: true,
  },
  {
    name: 'Mango Tango Smoothie',
    description: 'Fresh mango, banana and coconut, blended thick',
    price: 290,
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'cold',
    available: true,
  },
  {
    name: 'Pearl Milk Tea',
    description: 'Creamy milk tea with chewy tapioca pearls',
    price: 320,
    image: 'https://images.unsplash.com/photo-1558857563-b371033873b8?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'cold',
    available: true,
  },
  {
    name: 'Cinnamon Sugar Roll',
    description: 'Swirled brioche baked with cinnamon sugar and glaze',
    price: 220,
    image: 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'bakes',
    available: true,
  },
  {
    name: 'Dark Fudge Brownie',
    description: 'Fudgy dark-chocolate brownie, cracked top, cocoa nibs',
    price: 190,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'bakes',
    available: true,
  },
  {
    name: 'Loaded Avocado Toast',
    description: 'Sourdough, smashed avocado, chili crunch and lime',
    price: 280,
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'food',
    available: true,
  },
  {
    name: 'Croque Monsieur',
    description: 'Grilled ham and gruyère with bechamel, toasted golden',
    price: 340,
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?fm=jpg&q=80&w=700&auto=format&fit=crop',
    category: 'food',
    available: true,
  },
];